 // function generateRandomNumber() {
 //     var name = document.getElementById("name").value;
 //     var week = document.getElementById("week").value;
 //     var type = document.getElementById("type").value;
 //     var randomNumber;

 //     if (type === "Daily Devotion") {
 //         randomNumber = Math.floor(Math.random() * 16) + 15; // Generates random number between 15 and 30 for daily
 //     } else if (type === "Weekly Reading") {
 //         randomNumber = Math.floor(Math.random() * 15) + 1; // Generates random number between 1 and 15 for weekly
 //     }

 //     if (name && week && type) {
 //         var resultText = "Hello " + name +"; </br> Answer Question: " + randomNumber + " from week " + week + " of " + type + ". </br>Please  send screenshot to the group";

 //         document.getElementById("result").innerHTML = resultText;
 //         exportResultAsPdfOrJpg(resultText);
 //     } else {
 //         alert("Please fill in all fields.");
 //     }
 // }



document.getElementById('generateBtn').addEventListener('click', function() {
    var name = document.getElementById("name").value;
    var week = document.getElementById("week").value;
    var questionNumber = Math.floor(Math.random() * 30) + 1; // Generate a random number between 1 and 7

    var questions = {
        1: [
            "According to Luke chapter 1:3, who was the recipient of the book of Luke and what was the rationale for his writing?",
            "How was Zechariah chosen to serve as a priest before God?",
            "What happened to Zechariah when he doubted the prophesy given to him by Angel Gabriel?",
            "Mention 3 out of the prophesies given to Mary by the angel.",
            "What was Mary’s reply when the Angel said, “For no word from God will ever fail.",
            "What necessitated the parents of Jesus to return to Bethlehem before his birth and where was he born?",
            "According to Luke 2, who were the first to hear about Jesus' birth?",
            "According to Luke 2 what was the name of the righteous and devout man in Jerusalem waiting for the consolation of Israel and what was revealed to him by the Holy Spirit that will not happen to him before he had seen the Lord’s Messiah?",
            "According to Luke 2 when the time came for the purification rites as required by the Law of Moses the child Jesus was brought to Jerusalem to be presented to the Lord, there was also a prophet a widow, that never lee the temple but worshiped night and day, fasting and praying. What was her name and what were her uferances when the parents brought in the child Jesus to do for him what the custom of the Law required?",
            "Why did Mary and Joseph take Jesus to Jerusalem when he was twelve years old? After the event Jesus stayed behind in Jerusalem his parents searched for him and after three days they found him in the temple courts, sitting among the teachers, listening to them, and asking them questions, what did Jesus respond his parents with when they mentioned that they had been looking for him after they found him in the temple courts?",
            "What was the theme of John's preaching according to Luke 3:3?",
            "What was John's response to the Tax Collectors and the Soldiers when they asked him, saying 'Teacher, what should we do'?",
            "What was John's response to those who were wondering in their hearts if John might possibly be the Messiah?",
            "Why exactly did Herod lock John up in prison.",
            "A cursory look into the genealogy of Jesus according to the gospel of Luke, Jesus was traced back as the son of Most High how so?",
            "What did James mean when he said our life is like vapour?",
            "if our life is like vapour, how then should we spend it in wisdom?",
            "State the things that will matter and the ones that won’t matter to us at the end of our lifetime on earth.",
            "Describe how physical circumcision is done and on who it is done",
            "A man can be a Jew and yet not a Jew. Briefly explain.",
            "Use 'Jew' or 'Gentile' to fill in the gaps. For instance, Apostle Peter was a *Jew* biologically in the flesh, and a Jew Spiritually.  \n a. Apostle Paul was a _________ biologically in the flesh and a _________ spiritually in the heart.  \n b. Nicodemus of John 3 was a ________ biologically in the flesh and a ___________ spiritually in the heart.  \n c. As at when Paul wrote to them, the Ephesian believers were __________ biologically in the flesh and _______ spiritually in the heart.",
            "According to Ephesians 2 vs_____, the Gentiles in the flesh were called a mockery name of______ by______",
            "State three of the implications of being called that mockery name.",
            "We Gentiles were far from God in the past, but now that we believe, how close are we? Quote a Scripture to backup your answer.",
            "God does not dwell in temple. True or false? Briefly explain your answer.",
            "In Ephesians 2, state what the blood of Jesus did to us, and indicate the verse.",
            "Gentiles were called strangers in times past by the Jews, but now in Christ, we are called ________ by Jews who believe.",
            "Christ was called the Prince of Peace, how did he manifest this reality according to Ephesians 2?",
            "According to this teaching, why do we believers call ourselves brothers and sisters?",
            "The Jewish believers did not easily face the reality of the oneness we (Jews and Gentiles) all have in Christ. Cite an instance for this."

        ],
        2: [
            "According to Luke 4, state Jesus’ response for each of the temptations below : \n  a. The devil said to him, 'If you are the Son of God, tell this stone to become bread.' \n b. The devil led him up to a high place and showed him, in an instant, all the kingdoms of the world. And he said to him, 'I will give you all their authority and splendor; it has been given to me, and I can give it to anyone I want to. If you worship me, it will all be yours.' \n c. The devil led him to Jerusalem and had him stand on the highest point of the temple. 'If you are the Son of God,' he said, 'throw yourself down from here. For it is written: ‘He will command his angels concerning you to guard you carefully; they will lift you up in their hands,so that you will not strike your foot against a stone’.'",
            "According to Luke 4:17, whose scroll was handed to Jesus when he went into the synagogue?",
            "Referring to Luke 4:29, what was the reaction of all the people in the synagogue after Jesus was done teaching/speaking in the synagogue in Nazareth?",
            "What sickness did Jesus heal Simon’s mother-in-law from and what other miracles was done by Jesus in the town?",
            "What was Jesus’s reply according to Luke 4:43 when the people of the town tried to keep him from leaving them?",
            "List the miracles Jesus did in Luke 5?",
            "How did Simon Peter react to the miracle of a large number of fish he caught at the word of Jesus, and what did Jesus thereafter call Peter and his partners into?",
            "After Jesus healed the paralyzed man, he called a tax collector to follow him, what was the name of the said tax collector and how did he respond to Jesus’s call?",
            "What was the issue the Pharisees and teachers of the law complained to Jesus disciples about as regards his relationship with sinners and what was Jesus’s response to their complaint?",
            "What was Jesus’s response when he was questioned about his disciples not fasting and praying like the disciples of John the Baptist and the Pharisees?",
            "One Sabbath Jesus was going through the grainfields, and his disciples began to pick some heads of grain, rub them in their hands and eat the kernels. Some of the Pharisees asked, 'Why are you doing what is unlawful on the Sabbath ? \n'What was Jesus’s response to them (the pharisees)?",
            "According to Luke 6:12-14, Jesus went out to a mountainside to pray, and spent the night praying to God. When morning came, he called his disciples to him and chose twelve of them, whom he also designated apostles. Mention six out of the twelve disciples he chose?",
            "Complete the following statements:\n a. Blessed are you who are poor,..........................\n b. Blessed are you who hunger now,..........................\nc. Blessed are you who weep now,......................... ",
            "Jesus taught about Love walk in Luke 6, according to his teaching how are believers expected to relate with men especially our enemies. And who do we mirror when we love as Jesus instructed in his teaching? ",
            "According to Luke 6:48, what were those who go to Jesus, hear his words and put them into practice likened to?",
            "State the three areas of the tabernacle, and the items contained in each.",
            "State the categories of people allowed in each of the three areas of the tabernacle",
            "What other name was the Ark of covenant called, and state the things that were inside.",
            "The first earthly sanctuary of God was the _______, the second was the ______, and the current is the 	",
            "State two differences between the first and second earthly sanctuaries.",
            "The first temple was built by _____, and it was in existence for about _______. \n The second temple was built by _____ and later renovated by _______, and it was in existence for about _______years ",
            "Which of the temples was in existence in the time of Jesus?",
            "destroyed the first temple, and ______ destroyed the second temple.",
            "Before Jesus died, what was the right place for worshippers to offer sacrifices unto God, and why are we no more offering such sacrifices?",
            "What was the right direction of prayer before Jesus died, and why don’t we face that direction anymore?",
            "When did the veil of covering tear into two from top to bottom and state two of the significance of that incidence",
            "When the temple was still active, did all Jews have access into the Most Holy place, where God’s presence was? Briefly explain your answer.",
            "From first to last, arrange these in order of their existence; The temple of Herod, The Tabernacle of Moses, The temple of Solomon, The Body of Christ, The Heavenly Sanctuary, and state the ones that are still active today.",
            "According to this teaching, how did God make it clear that there is no difference between the Jews and Gentiles.",
            "Who is the High Priest of the Current Sanctuary, where is he seated and what is he doing?"
        ],
        3: [
            "How did the Centurion exercise great faith according to Luke 7?",
            "According to Luke 7:19-22, how did Jesus reply to the disciples of John the Baptist whom he sent to ask Jesus if he is the one who is to come, or if they should expect someone else?",
            "Referring to Luke 7:30, who were those that rejected God’s purpose for themselves, because they had not been baptized by John?",
            "One of the Pharisees invited Jesus to have dinner with him, when Jesus got to his house, what did the woman with alabaster jar of perfume do to him?",
            "What was Simon's answer when Jesus asked him a question regarding the two debtors owing a money lender on forgiving both debtors?",
            "In Luke 8:1-3 it was recorded that Jesus travelled about from one town and village to another, proclaiming the good news, who were the women mentioned in that verse that accompanied Jesus with his disciples?",
            "What was Jesus’ response when someone told him, “Your mother and brothers are standing outside, wanting to see you.”?",
            "What miracle did Jesus perform in a boat on the Sea/lake of Galilee?",
            "In the story of the demon-possessed man, where did the demons ask Jesus to send them after being cast out?",
            "What was Jesus’ response to Jairus when he was told “Your daughter is dead, don’t bother the teacher anymore.”?",
            "What did Jesus sent out his 12 disciples to do after giving them power and authority over all devils, and to cure diseases according to Luke 9:2?",
            "Why was Herod the tetrarch perplexed according to Luke 9:7 & 9?",
            "Where did Jesus fed about ﬁve thousand (5000) people with only 5 loaves of bread and 2 ﬁshes, and how many baskets of broken pieces were left over?",
            "And Jesus asked his disciples, saying, “whom say the people that I am”, what was their response and what was Peter’s response?",
            "After the two men (Moses and Elias) had departed from him (Jesus), what did Peter said to Jesus according to Luke 9:33?",
            "State three facts about Sin",
            "Digerentiate between Sin and Trespass",
            "What does the word “dead” in Ephesians 2:1 imply?",
            "The salvation that the sugering and death of Jesus brought is for men, not angels. Explain why.",
            "Why did Christ die, and what was His death meant to achieve",
            "Use your life as a believer to digerentiate between “dead in” and “dead with”.",
            "Use your life as a believer to digerentiate between “dead in” and “dead with”.",
            "Digerentiate between “dead with” and “dead to”",
            "Believers were dead	sin while unbelievers are dead	sin",
            "In terms of purpose, how is Christ’s death peculiar, as compared with other people’s death?",
            "How did Jesus terminate our relationship with sin?",
            "It is one earth, one Jesus. Use a scripture to explain that.",
            "Why is it not foolishness and waste of time to preach about a Jesus that died 2000 years ago?",
            "Christ died for all men, therefore, all men are automatically saved. True or False? Brieﬂy explain your answer.",
            "What is the gospel message that saves men?",
            "According to this teaching, state the four things that happened to us together with Christ."
        ],
        4: [
            "In Luke 10 Jesus appointed and sent out the seventy, in what pair were they sent and what was the first thing they are to say whenever they enter a house?",
            "According to Luke 10:17-18 the seventy that was sent out returned with joy and said, “Lord, even the demons submit to us in your name. Jesus told them not to mainly rejoice because of that but what should they rather rejoice over?",
            "In Luke 10 a certain lawyer tested Jesus and asked what he must do to inherit eternal life, following the conversation that ensued between parties what was the answer to the question the Lawyer asked?",
            "According to Luke 10, which one of the three men that passed by was a neighbor to the man who fell into the hands of robbers?",
            "Referring to Luke 10:38-42, Martha who was distracted complained to the Lord that Mary her sister who sat at the Lord’s feet listening to what he said, left her to do all the preparation that had to be made by herself, what was Jesus’ response after she told him to instruct Mary to help her?",
            "What did Jesus say about the nature of God in Luke 11?",
            "When Jesus was casting out demon, what did some of the crowd think Jesus was using to cast out demon and what was Jesus’ reply?",
            "What sign does Jesus say will be given to the people in Luke 11?",
            "Who does Jesus say is blessed in Luke 11?",
            "In Luke 11:50-51 Jesus was declaring woes to the experts of law and mentioned that their generation will be held responsible for the blood of all the prophets that has been shed since the beginning of the world. What are the names of the prophets mentioned by Jesus in this verse?",
            "Whom did Jesus tell his disciples not to be afraid of and whom did he forewarn them to fear according to Luke 12:4-5 and in extension to us?",
            "According to Luke 12:10, which sin shall be forgiven, and which sin shall not be forgiven?",
            "What was Jesus’ response to the man who said to him, 'Teacher, tell my brother to divide the inheritance with me'?",
            "What did Jesus tell his disciples not to worry about but rather what should be sought after?",
            "In Jesus’ teaching on watchfulness, he used Servant and Master analogy going by that illustration according to Luke 12:47, who shall be beaten with many blows/stripes?",
            "What does it mean that Jesus bore our sins in his body?",
            "State three of the things that happened from the point of Jesus’ condemnation to the point of his death.",
            "Describe how these categories of people mocked Jesus: (a) the soldiers (b) the passers-by (c) the chief priests",
            "Compare Jesus with the two goats offered in the Old Testament for sins of people.",
            "According to *1 Peter 2:24*, state two things Christ’s suffering and death was meant to achieve",
            "What did Jesus mean when he said 'Ye shall know the truth and the truth shall make you free'?",
            "If it is true that Jesus saved us from sin, how then do we explain a believer who is still living in sin?",
            "'If a man has the Holy Spirit, he will never be able to sin again'. What’s your opinion?",
            "Ǫuote a Scripture that states how a believer can avoid being controlled and influenced by sin.",
            "State three things “the flesh” can mean in the Scriptures",
            "Describe believers past and present relationship with the flesh",
            "The moment a believer gets born again, the flesh will stop its advances. How true is that scripturally?",
            "What does it mean to walk in the Spirit?",
            "Once a man is born again, he instantly begins to walk in the Spirit. How true is that?",
            "Believers are slaves. Briefly explain."
        ],
        5: [
            "Why did the ruler of the synagogue where Jesus taught in Luke 13 answer the people with indignation?",
            "What healing was done by Jesus in Luke 13?",
            "Mention one of the things Jesus compared the kingdom of God with.",
            "What did Jesus replied with when some Pharisees came to him and said to him, to leave where he was and go somewhere else because Herod want to kill him?",
            "In Luke 13, what did Jesus say about Jerusalem",
            "Whose house did Jesus go to eat on one Sabbath day in Luke 14?",
            "What lesson did Jesus teach about humility in Luke 14?",
            "Who did Jesus suggest should be invited to a banquet, according to Luke 14?",
            "What did Jesus say about the cost of discipleship in Luke 14?",
            "State one of the analogies Jesus used to illustrate the importance of counting the cost of discipleship",
            "How many parables was said by Jesus in Luke 15 and mention them?",
            "In the parable of the lost coin/piece of silver, what did the woman say to her friends and neighbors after she found her missing coin/piece of silver?",
            "What brings about rejoicing in the presence of the angels of God according to Luke 15?",
            "In the parable of the lost son what did the younger son demand of their father and how did he make use of it not long after it was given to him?",
            "According to the parable of the lost son, why was the older son angry and refused to go in and what did the father say to him?",
            "State the natural and spiritual meaning of the word 'carnal'",
            "How can a believer be spiritual and yet carnal? ",
            "What is the first thing a believer who wants to walk in the Spirit must know?",
            "According to this teaching, what is walking in the Spirit all about?",
            "Jesus answered them, ‘It is not the healthy who need a doctor, but *the sick*. Who did Jesus refer to as ‘the doctor’ and ‘the sick’, and what’s the implication?",
            "Believers must not get close to sinners, so that they won’t be inﬂuenced. How aligned is that statement with the Scriptures?",
            "What would you say to a believer who wants to marry an unbeliever in order to get him/her saved?",
            "According to 1 Peter 2:24, what were we healed from, and how did we get healed?",
            "Does a believer need to change his way of life once he gets saved? (2) What does it mean to put oﬀ the old man?",
            "What does it mean to put oﬀ the old man?",
            "26.	According to Ephesians chapters 4 and 5, state two examples of things a believer must put oﬀ.",
            "'Do not partner with sinners'. What does it mean, and what does it not mean?",
            "Which believing brother or sister are we warned not to associate with?",
            "Since we are forgiven in Christ for our past, present and future sins, it therefore doesn’t matter if believers sin. Scripturally argue that ideology.",
            "Give example of a Biblical figure who ran away from secret sin and another example of one who committed it."

        ],
        6: [
            "How many parables are in the Luke 16, mention them",
            "What was the reaction of the unjust servant who wasted his master’s possession when his master called him to give account of his stewardship as he will longer work for him.",
            "'Whoever can be trusted with very little can also be trusted with much, and whoever is dishonest with very little will also be dishonest with much. So if you have not been trustworthy in handling worldly wealth, who will trust you with true riches? And if you have not been trustworthy with someone else’s property, who will give you property of your own?'\n Who made the above statement and in what teaching in Luke 16 is it related to? ",
            "In Luke 16 Jesus taught on divorce what was his stand on the same.",
            "What was Abraham's response when the rich man asked him to send Lazarus to his family?",
            "What did Jesus teach about forgiveness in Luke 17?",
            "How did Jesus respond to his disciple’s request for increased faith in Luke 17?",
            "In Luke 17, how many men with Leprosy did Jesus heal and how many came back to give thanks?",
            "Describe how Jesus compared the days of his coming to the days of Noah.",
            "Describe how Jesus compared the days of his coming to the days of Lot.",
            "According to Luke 18:1-7, Jesus told his disciples the parable of the persistent widow, what was the lesson in the parable?",
            "What was the rationale behind the parable of the Pharisee and tax collector Jesus told in Luke 18.",
            "Fill in the gaps according to Luke 18:14, 'For those who______themselves will be_______, and those who______themselves will be_________'",
            "What was Jesus’ reaction when the disciples rebuked the people who brought children to him for him to place his hands on them?",
            "A rich ruler came to Jesus to ask about how he would inherit the kingdom of God. Why did he become sad upon making his inquiry?",
            "How did Nicodemus interpret the term “born again”, and what was the right interpretation of it?",
            "In John 3:5, Jesus said “Except a man be born of water and of the Spirit”. That means, water baptism is required to be born again. How true is that?",
            "What is another phrase we can use for “born again” and quote a Scripture that used that other phrase.",
            "Are you saved? Are you born again? Quote a Scripture for each.",
            "Quote a Scripture that says a sister who does not wear make-up, earring or use attachment is born again.",
            "Quote a scripture to show that being born of a great man of God does not imply being born-again",
            "By whose will did we become born again?",
            "A believer who still struggles with a sin needs to be reborn again. Discuss.",
            "Being saved and being born again are the same thing. Discuss.",
            "Both Zachariah and Mary questioned God’s word, one was made dumb and the other was not, why?",
            "State two things that happen instantaneously when a man believes the gospel",
            "If it be possible for salvation to be lost, what other things will be lost?",
            "Quote a scripture that stands as an insurance policy of our salvation.",
            "What did we see in *Hebrews 7:25* that assures us of Jesus’ ability to save us to the uttermost?",
            "If a believer loses his salvation, then God is a liar. Discuss."
        ],
        7: [

            "In Luke 19 Jesus entered Jericho and was passing through there was a Chief tax collector and wealthy man in that land what was his name and what was his action that greatly showed his desire to see who Jesus was?",
            "What was Jesus’ response when Zacchaeus stood up and said to Him, 'Look, Lord! Here and now I give half of my possessions to the poor, and if I have cheated anybody out of anything, I will pay back four times the amount.'",
            "In Luke 19 Jesus instructed two of his disciples to go to the village ahead of them, when they enter, they will find a colt tied there, which no one has ever ridden. They should untie it and bring it him. He further stated that if anyone asks them, ‘Why are you untying it?’ what did Jesus said their response should be?",
            "What was Jesus’ response to some of the Pharisees in the crowd that said to him to rebuke the multitude of his disciples that were joyfully praising God in loud voices for all the miracles they had seen as Jesus triumphantly entered Jerusalem?",
            "When Jesus entered the temple courts in Luke 19, whom did he drive out and what did he say to them while doing so.",
            "What did the chief priests, the teachers of the law and the elders, question Jesus about in Luke 20?",
            "In the parable of the tenant, what did the tenants do to the 1st servant, 2nd servant, 3rd servant and the only son of the owner of the Vineyard?",
            "How did Jesus respond to the question about paying taxes in Luke 20:24-25?",
            "How did Jesus respond to the Sadducees' question about the resurrection in Luke 20?",
            "What warning did Jesus give against the Teachers of the Law Luke 20?",
            "When the rich were putting their gift in the temple treasury, there was a certain poor widow who also put in two very small copper coins, but Jesus said the widow has put in more than all the others. Why?",
            "According to Luke 21 mention 3 signs of the end time.",
            "In Luke 21:13 – 14 Jesus prepared the mind of his disciples on the coming persecution that would befall them on bearing testimony of Christ, what further instruction did he give to them on what they would say when they are brought before kings and governors on account of his name?",
            "In Luke 20:21-22 Jesus spoke on the great wrath that would befall the land of Jerusalem, he mentioned to his disciples that when they see Jerusalem being surrounded by armies, they will know that its desolation is near. What warning was given by Jesus to his disciples to take heed of in order not to experience the great wrath that will befall the land.",
            "What did Jesus say about the parable of the fig tree and what does it imply?",
            "State the two kinds of righteousness we have and how each can be gotten.",
            "Ezekiel 3:20 talks about how sin can make a righteous man to lose his salvation. How do we explain with the scriptural stand that our salvation can’t be lost?",
            "It is true that righteousness can be lost, and it is also true that righteousness can’t be lost. Explain.",
            "In 1 Corinthians 9:27, Paul said “lest that by any means, when I have preached to others, I myself should be a castaway”. The word “castaway” means to lose salvation. Explain.",
            "A man can believe that Jesus is the Christ and yet not be saved. Explain.",
            "If Christ did not rise from the dead, state two things that would be in vain.",
            "1 Corinthians 15:1-2 says “by which also ye are saved, if ye keep in memory what I preached unto you, unless ye have believed in vain”. How can a man believe in Jesus as the Christ, and yet that believing would be in vain?",
            "In 2 Timothy 4:10, Demas forsook Paul, therefore he lost his salvation. Discuss.",
            "The Bible says in *1 John 2:15* that we should not love the world, same Bible says in *John 3:16* that “for God so loved the world”. Why will God love the world and ask us not to?",
            "*Acts 5:11* “And great fear came upon all the church, and upon as many as heard these things”. Using this verse, can we say Ananias and Sapphira were saved or not?",
            "State two lessons we can learn from the death of Ananias and Sapphira",
            "Jesus made a mistake by choosing Judas as one of his twelve apostles. Discuss",
            "State three bad names Judas Iscariot was called in the Bible.",
            "Judas lost his salvation. Discuss.",
            "Both Peter and Judas sinned against Jesus, but only Peter was restored. Why?"
        ],
        8: [
            "What feast/festival was celebrated in Luke 22.",
            "Which of the disciples agrees to betray Jesus? How did he show/betray Jesus to the Chief priests, the officers of the temple guard and elders who had come for him? And what did they promise to reward him with upon accomplishment of the betrayal assignment according to Luke 22?  ",
            "What appointment was given to the twelve Apostles by Jesus in His kingdom for standing by him in his trials and temptation according to Luke 22?",
            "With your understanding on the conversation that ensued between Jesus and Simon in Luke 22 before his betrayal answer the following questions.\nJesus revealed unto Simon how  Satan has asked to sift all of them(Apostles) as wheat. But He has prayed for Simon, that his  faith may not fail.\n How many times did Jesus say Simon would deny him and was this fulfilled before rooster crow as Jesus foretold? \n What did Jesus instruct him to do after he turned back/ returned to the fold?",
            "Upon Jesus arrest and was brought before Pilate and Herod when the council of the elders of the people, both the chief priests and the teachers of the law, met together, and he was led before them. They asked Jesus if is the Son of God, what was Jesus’ reply?",
            "What was Pilate's Judgement on Jesus in Luke 23:13-16?",
            "What did the crowd cry out to be done to Jesus and whom did they shout to be released in place of Jesus in Luke 23?",
            "How did one of the criminals crucified with Jesus got saved/ receive salvation in Luke 23?",
            "What event happened in Luke 23 when Jesus was about to breathe his last on the cross in Luke 23?",
            "What’s the name of the man that provided a tomb for Jesus' burial and how was he described in Luke 23?",
            "What were the names of the women that was mentioned among other women that went early morning with spices they had prepared the tomb where the body of Jesus was laid? And what day of the week did they go?",
            "When the women got to the tomb, they found the stone rolled away from the tomb and they did not find the body of the Lord Jesus in the tomb, they thereafter had an encounter with two men in clothes that gleamed like lightening. What did the men tell them and what were the words of Jesus that was brought to the women’s remembrance by the men they had encounter with?",
            "Why were the disciples frightened at the sight of Jesus when he appeared to them after his resurrection?",
            "How did Jesus prove to them he resurrected and that he isn’t a spirit?",
            "Before Jesus’ ascension to heaven, which city did he instruct his disciples to tarry in until they have been endued with power from on high?"
        ],
        9: [
            "According to Luke chapter 1:3, who was the recipient of the book of Luke and what was the rationale for his writing?",
            "How was Zechariah chosen to serve as a priest before God, and what service was he given?",
            "What happened to Zechariah when he doubted the prophesy given to him by Angel Gabriel?",
            "Mention 3 out of the prophesies given to Mary by the angel.",
            "What was Mary’s reply when the Angel said, “For no word from God will ever fail.”",
            "What necessitated the parents of Jesus to return to Bethlehem before his birth and where was he born?",
            "According to Luke 2, who were the ﬁrst to hear about Jesus' birth?",
            "According to Luke 2 what was the name of the righteous and devout man in Jerusalem waiting for the consolation of Israel and what was revealed to him by the Holy Spirit that will not happen to him before he had seen the Lord’s Messiah?",
            "According to Luke 2 when the time came for the puriﬁcation rites as required by the Law of Moses the child Jesus was brought to Jerusalem to be presented to the Lord, there was also a prophet a widow, that never left the temple but worshiped night and day, fasting and praying. What was her name and what were her utterances when the parents brought in the child Jesus to do for him what the custom of the Law required?",
            "Why did Mary and Joseph take Jesus to Jerusalem when he was twelve years old? After the event Jesus stayed behind in Jerusalem his parents searched for him and after three days they found him in the temple courts, sitting among the teachers, listening to them, and asking them questions, what did Jesus respond his parents with when they mentioned that they had been looking for him after they found him in the temple courts?",
            "Luke was not the ﬁrst person to write about the story of the Lord Jesus Christ. And in fact, before he wrote his gospel book, many people have already written about the same. Use a Scripture to establish this fact.",
            "It is possible to be living righteous before God, and yet have problems in this life. Use the case of Zachariah and Elisabeth as instance.",
            "The Old Testament books ended with this prophecy; Malachi 4:5-6 'Behold, I will send you Elijah the prophet before the coming of the great and dreadful day of the LORD: And he shall turn the heart of the fathers to the children, and the heart of the children to their fathers, lest I come and smite the earth with a curse' \n According to Luke’s gospel, who fulﬁlled that prophecy in the New testament.",
            "According to the gospel of Luke, name the gifts given to Jesus by the local shepherds that visited him when he was born in a manger.",
            "Luke 2:3-4 called Bethlehem of Judea the city of Jesus’ parents, while Luke 2:39 said Nazareth of Galilee was their city. How do we balance these two contradictory statements?",
            "Only believers who believe that salvation can’t be lost will get to heaven. True or False? Brieﬂy explain your answer.",
            "Who were those Jesus was speaking about in Matthew 7:21-23 when he said many who prophesied in his name will not enter into the kingdom of heaven?",
            "Why will the Lord say “I never knew you” in *Matthew 7:21-23* to those who prophesied and did signs and wonders in his name?",
            "Why is the pronoun “whom” used for the Holy Spirit in Ephesians 4:30 instead of the pronoun “which”.",
            "How did God reveal that you are his property, and that he owns you?",
            "If a believer sins, the Holy Spirit will leave. How true is that?",
            "What determines the activeness of the Holy Spirit in a believer?",
            "The Holy Spirit doesn’t care if a believer lives an unholy life. Discuss.",
            "State the two cautions the Scriptures give us in our relationship with the Holy Spirit",
            "How can believer(s) quench the Spirit?",
            "The Holy Spirit can experience emotional pain or sorrow. How?",
            "State three examples of things that can serve as ﬁre extinguishers to the Spirit of God.",
            "How can we reignite the ﬁre of God’s Spirit?",
            "A believer who is not in fellowship with God has lost his Father-Son relationship with God. Discuss",
            "State two elects of being out of fellowship with God."
        ],
        10: [
            "When Jesus was born in Luke 2:1, Luke mentioned Caesar Augustus, but on getting to Luke 3:1, he mentioned Tiberius Caesar. What understanding can we deduct from that context?",
            "What was the theme of John's preaching according to Luke 3:3?",
            "What was John's response to the Tax Collectors and the Soldiers when they asked him, saying 'Teacher, what should we do '?",
            "What was John's response to those who were wondering in their hearts if John might possibly be the Messiah?",
            "Why exactly did Herod lock John up in prison.",
            "God bore witness of His Son in river Jordan. Briefly explain.",
            "A cursory look into the genealogy of Jesus according to the gospel of Luke, Jesus was traced back as the son of Most High how so?",
            "God does not tempt believers, but he can lead believers into temptation. Use Jesus as instance.",
            "According to Luke 4, state Jesus’ response for each of the temptations below : \n a.The devil said to him, 'If you are the Son of God, tell this stone to become bread.' \n b.The devil led him up to a high place and showed him, in an instant, all the kingdoms of the world. And he said to him, 'I will give you all their authority and splendor; it has been given to me, and I can give it to anyone I want to. If you worship me, it will all be yours.' \n c.The devil led him to Jerusalem and had him stand on the highest point of the temple. 'If you are the Son of God,' he said, 'throw yourself down from here. For it is written: ‘He will command his angels concerning you to guard you carefully; they will lift you up in their hands,so that you will not strike your foot against a stone’.' ",
            "According to Luke, where was Jesus brought up, and what was his custom as he grew?",
            "According to Luke 4:17, whose scroll was handed to Jesus when he went into the synagogue?",
            "Referring to Luke 4:29, what was the reaction of all the people in the synagogue after Jesus was done teaching/speaking in the synagogue in Nazareth?",
            "What sickness did Jesus heal Simon’s mother-in-law from and what other miracles was done by Jesus in the town?",
            "What was Jesus’s reply according to Luke 4:43 when the people of the town tried to keep him from leaving them?",
            "In Luke 9:18-19, people did not know who Jesus was. But, according to Luke 4:41, the devils knew who he was. Who did the devils say Jesus was?",
            "Differentiate between Hebrews, Israelites, and Jews",
            "Classify the following Bible Characters as Jew, Israelite, or Hebrew. Some can belong to two or three of those classes, indicate in such case. (a) Jesus (b) Isaac (c) Joseph (d) Abraham (e) Paul.",
            "When the children of Jacob were in Egypt, God was called the God of___________. When they left Egypt and became a nation, He was called the God of___________. In the latter part of the Old Testament, and early part of the New Testament, he was called the God of___________. Finally, in the epistle, he was called the God of .",
            "Romans 9:13 says, “As it is written, Jacob have I loved, but Esau have I hated”. What does it mean that God loved Jacob and hated Esau?",
            "God is the God of the Jews only. Discuss.",
            "All Jews are Israelites, and all Israelites are Jews. True or False. Brieﬂy explain your answer.",
            "Scripturally, classify these groups as circumcised and uncircumcised. (a) Samaritans (b) Corinthians (c) Jews (d) Nigerians (e) Israelites ",
            "We can’t talk about salvation without talking about the Jews. Discuss",
            "State two similar things God did for both Jews and Gentiles that showcased oneness among the two?",
            "What was the main cause of division between the Circumcised Jews and Uncircumcised Gentiles",
            "What did Jesus do to the barrier that divided the Jews and Gentiles, and how did he do it?",
            "Jesus made peace between the circumcised and the uncircumcised. If we are trying to make peace between individuals, and we desire to do it the way Jesus did it, what must be dealt with for the peace to be achieved?",
            "With reference to circumcision, what is the di[erence between a proselyte and a gentile believer.",
            "Complete this statement, in Christ Jesus, Circumcision is   _________, and uncircumcision is_________",
            "How dangerous is it for a believer to be ignorant of the truth of what Christ had already done for him?"
        ],
        11: [
            "'Launch out into the deep, and let down your nets for a draught'. Briefly narrate the context behind that statement, stating what happened before and after the statement was made. ",
            "According to Luke 5:10, what was the relationship between Simon Peter, James Zebedee and John Zebedee before they met Jesus?",
            "Luke 5:20 says “And when he (Jesus) saw their faith”. That means faith can be seen. How did Jesus see the faith of those men in Luke 5?",
            "List the miracles Jesus did in Luke 5?",
            "How did Simon Peter react to the miracle of a large number of fish he caught at the word of Jesus, and what did Jesus thereafter call Peter and his partners into?",
            "After Jesus healed the paralyzed man, he called a tax collector to follow him, what was the name of the said tax collector and how did he respond to Jesus’s call?",
            "What was the issue the Pharisees and teachers of the law complained to Jesus disciples about as regards his relationship with sinners and what was Jesus’s response to their complaint?",
            "What was Jesus’s response when he was questioned about his disciples not fasting and praying like the disciples of John the Baptist and the Pharisees?",
            "One Sabbath Jesus was going through the grainfields, and his disciples began to pick some heads of grain, rub them in their hands and eat the kernels. Some of the Pharisees asked, 'Why are you doing what is unlawful on the Sabbath ? \n 'What was Jesus’s response to them (the pharisees)?",
            "In Luke 6, narrate how both Jesus and his disciples broke the law of the sabbath. ",
            "According to Luke 6:12-14, Jesus went out to a mountainside to pray, and spent the night praying to God. When morning came, he called his disciples to him and chose twelve of them, whom he also designated apostles. Mention six out of the twelve disciples he chose?",
            "Complete the following statements: \n a. Blessed are you who are poor,............... \n b. Blessed are you who hunger now,............... \n c. Blessed are you who weep now,.............",
            "Jesus taught about Love walk in Luke 6, according to his teaching how are believers expected to relate with men especially our enemies. And who do we mirror when we love as Jesus instructed in his teaching?",
            "According to Luke 6, if every tree is known by his own fruit, how is every man known?",
            "According to Luke 6:48, what were those who go to Jesus, hear his words and put them into practice likened to? ",
            "According to Ephesians 2:11-22, state three things the death of Jesus on the cross did for both the circumcised and uncircumcised. ",
            "Paul was a Jew, yet, in his epistles to the gentile churches, he used the term “brethren” for them. How did they become his brethren?  ",
            "Only the Gentiles need to be reconciled to God, not the Jews. Discuss ",
            "On the subject of God’s leading, which is better, to PRAY FOR a believer or to PRAY WITH a believer? And state your why",
            "Use a scripture to oppose the ideology of believers saying “Man of God, we are too small to pray for you”. ",
            "According to Ephesians 4, state one of the reasons why God gave us men of God.",
            "Saints are perfect and sinless people. Briefly discuss. ",
            "Who were the saints of God in the Old Testament, and who are the saints in the New Testament? ",
            "We are citizens of heaven by birth. Briefly discuss.  ",
            "Blocks and iron rods were used in constructing the Herod’s temple of Jesus’ time. Discuss ",
            "Differentiate between foundational stones and cornerstone. ",
            "State three ways in which Isaiah described the cornerstone. ",
            "Differentiate between the material used for the physical temple and the ones used for the spiritual temple. ",
            "In God’s Spiritual Temple, name the cornerstone, the foundation stones, and the building stones. ",
            "Currently, where does God dwell by His Spirit?"
        ]
    };

    var question = questions[week][questionNumber - 1]; // Get the question for the selected week
    var output = "Hello " + name + ";  Answer Question Number " + questionNumber + " from week " + week + ". \n\n QUESTION: " + question + "  \n\n Send screenshot to the group. Thanks!";



    document.getElementById('output').innerText = output;
});
